#! /bin/sh

if ! which dch >/dev/null; then
	echo >&2 "please install devscripts"
	exit 1
fi

if ! which debootstrap >/dev/null; then
	echo >&2 "please install debootstrap"
	exit 1
fi

germinate-update-metapackage --bzr

# a workaround to keep the desired package names
sed -i 's/elementary-seed-/elementary-/g' metapackage-map
