#!/bin/bash

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'Adds package names to seed files parsed by Germinate'
    echo 'Usage: '$(basename $0)' section package-name [package-name]...'
    echo 'section examples: "minimal", "desktop-recommends"'
    exit 1
fi

section="$1"
shift

while [ "$1" != "" ]; do
    for arch in i386 amd64 armel powerpc lpia; do
        for file in $section-$arch; do
            if [ -f "$file" ]; then
                echo $1 >> "$file"
                cat "$file" | uniq | sort > "$file".tmp
                mv --force "$file".tmp "$file"
            fi
        done
    done
shift
done
